/**
 * Proof of possession: turning a credential from a bearer token into a key.
 *
 * A credential alone proves only that Infinity issued a mandate. Anything that
 * copies it can present it. Possession is what binds the credential to the agent
 * actually on the wire, so this module defines the one string both sides sign and
 * check, and nothing else.
 *
 * Pure: no dependencies, no server imports, no secrets. A verifier vendors this
 * file alongside `jws.ts` and `credential.ts`.
 */

import { b64uEncode, parseStoredPublicKey, sha256Hex, verifyRawEd25519 } from "./jws";

export const POP_VERSION = "INFINITY-POP-v1";

export type ProofParts = {
  /** Single-use nonce, generated by whoever is doing the verifying. */
  nonce: string;
  /** Uppercased HTTP method, or a verb like "MCP" for non-HTTP channels. */
  method: string;
  /** Absolute URL, or a stable resource name for non-HTTP channels. */
  url: string;
  /** Lowercase hex SHA-256 of the request body. Empty string when there is none. */
  bodySha256: string;
};

/**
 * The exact bytes that get signed.
 *
 * Newline-separated with a version tag first. Each field is on its own line and
 * newlines are rejected inside fields, so no field can absorb another — the same
 * canonicalisation failure that the v1 event hash had.
 */
export function canonicalProofString(parts: ProofParts): string {
  for (const [key, value] of Object.entries(parts)) {
    if (/[\r\n]/.test(value)) throw new Error(`Proof field "${key}" must not contain a newline.`);
  }
  return [POP_VERSION, parts.nonce, parts.method.toUpperCase(), parts.url, parts.bodySha256].join(
    "\n",
  );
}

/** Hash a request body for inclusion in the proof. Empty body hashes to "". */
export async function bodyHash(body: string | undefined | null): Promise<string> {
  if (!body) return "";
  return sha256Hex(body);
}

/**
 * Generate a challenge nonce.
 *
 * The *verifier* calls this, which is the point: the nonce never comes from us,
 * so checking an agent needs no round trip to Infinity and no replay state we
 * have to hold on the verifier's behalf.
 */
export function createChallenge(): string {
  return b64uEncode(crypto.getRandomValues(new Uint8Array(32)));
}

/** Agent side: sign the canonical string with the agent's own key. */
export async function signProof(privateKey: CryptoKey, parts: ProofParts): Promise<string> {
  const message = new TextEncoder().encode(canonicalProofString(parts));
  const signature = await crypto.subtle.sign(
    { name: "Ed25519" },
    privateKey,
    message as unknown as BufferSource,
  );
  return b64uEncode(new Uint8Array(signature));
}

export type ProofResult = { ok: true } | { ok: false; reason: ProofFailure };

export type ProofFailure =
  "malformed_public_key" | "malformed_signature" | "bad_proof_signature" | "malformed_proof";

export const PROOF_FAILURE_TEXT: Record<ProofFailure, string> = {
  malformed_public_key: "The public key in the credential could not be read.",
  malformed_signature: "The proof signature could not be decoded.",
  bad_proof_signature: "The presenter does not hold the key named in the credential.",
  malformed_proof: "The signed material was not well formed.",
};

/**
 * Verifier side: check that the presenter holds the private half of the key the
 * credential names.
 *
 * `storedPublicKey` must come from *inside the verified credential*, never from
 * the request — otherwise the presenter chooses the key it is checked against,
 * which proves nothing.
 */
export async function verifyProof(
  storedPublicKey: string,
  signatureB64u: string,
  parts: ProofParts,
): Promise<ProofResult> {
  const rawKey = parseStoredPublicKey(storedPublicKey);
  if (!rawKey) return { ok: false, reason: "malformed_public_key" };

  let message: Uint8Array;
  try {
    message = new TextEncoder().encode(canonicalProofString(parts));
  } catch {
    return { ok: false, reason: "malformed_proof" };
  }

  let signature: Uint8Array;
  try {
    const padded = signatureB64u.replace(/-/g, "+").replace(/_/g, "/");
    const withPad = padded + (padded.length % 4 === 0 ? "" : "=".repeat(4 - (padded.length % 4)));
    const binary = atob(withPad);
    signature = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) signature[i] = binary.charCodeAt(i);
  } catch {
    return { ok: false, reason: "malformed_signature" };
  }
  if (signature.length !== 64) return { ok: false, reason: "malformed_signature" };

  const ok = await verifyRawEd25519(message, signature, rawKey);
  return ok ? { ok: true } : { ok: false, reason: "bad_proof_signature" };
}
