/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as DotwellKnownInfinityIssuerDotjsonRouteImport } from './routes/[.]well-known.infinity-issuer[.]json'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known.jwks[.]json'
import { Route as VerifyAgentIdRouteImport } from './routes/verify.$agentId'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as ApiPublicCredentialAgentIdRouteImport } from './routes/api/public/credential.$agentId'
import { Route as ApiPublicStatusAgentIdRouteImport } from './routes/api/public/status.$agentId'
import { Route as ApiPublicVerifyAgentIdRouteImport } from './routes/api/public/verify.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownInfinityIssuerDotjsonRoute =
  DotwellKnownInfinityIssuerDotjsonRouteImport.update({
    id: '/.well-known/infinity-issuer.json',
    path: '/.well-known/infinity-issuer.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAgentIdRoute = VerifyAgentIdRouteImport.update({
  id: '/verify/$agentId',
  path: '/verify/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCredentialAgentIdRoute =
  ApiPublicCredentialAgentIdRouteImport.update({
    id: '/api/public/credential/$agentId',
    path: '/api/public/credential/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStatusAgentIdRoute = ApiPublicStatusAgentIdRouteImport.update({
  id: '/api/public/status/$agentId',
  path: '/api/public/status/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyAgentIdRoute = ApiPublicVerifyAgentIdRouteImport.update({
  id: '/api/public/verify/$agentId',
  path: '/api/public/verify/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/.well-known/infinity-issuer.json': typeof DotwellKnownInfinityIssuerDotjsonRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/verify/$agentId': typeof VerifyAgentIdRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/api/public/credential/$agentId': typeof ApiPublicCredentialAgentIdRoute
  '/api/public/status/$agentId': typeof ApiPublicStatusAgentIdRoute
  '/api/public/verify/$agentId': typeof ApiPublicVerifyAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/.well-known/infinity-issuer.json': typeof DotwellKnownInfinityIssuerDotjsonRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/verify/$agentId': typeof VerifyAgentIdRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/api/public/credential/$agentId': typeof ApiPublicCredentialAgentIdRoute
  '/api/public/status/$agentId': typeof ApiPublicStatusAgentIdRoute
  '/api/public/verify/$agentId': typeof ApiPublicVerifyAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/.well-known/infinity-issuer.json': typeof DotwellKnownInfinityIssuerDotjsonRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/verify/$agentId': typeof VerifyAgentIdRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/api/public/credential/$agentId': typeof ApiPublicCredentialAgentIdRoute
  '/api/public/status/$agentId': typeof ApiPublicStatusAgentIdRoute
  '/api/public/verify/$agentId': typeof ApiPublicVerifyAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/.well-known/infinity-issuer.json'
    | '/.well-known/jwks.json'
    | '/verify/$agentId'
    | '/agents/$id'
    | '/agents/new'
    | '/agents/'
    | '/api/public/credential/$agentId'
    | '/api/public/status/$agentId'
    | '/api/public/verify/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/.well-known/infinity-issuer.json'
    | '/.well-known/jwks.json'
    | '/verify/$agentId'
    | '/agents/$id'
    | '/agents/new'
    | '/agents'
    | '/api/public/credential/$agentId'
    | '/api/public/status/$agentId'
    | '/api/public/verify/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/.well-known/infinity-issuer.json'
    | '/.well-known/jwks.json'
    | '/verify/$agentId'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/agents/'
    | '/api/public/credential/$agentId'
    | '/api/public/status/$agentId'
    | '/api/public/verify/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  DotwellKnownInfinityIssuerDotjsonRoute: typeof DotwellKnownInfinityIssuerDotjsonRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  VerifyAgentIdRoute: typeof VerifyAgentIdRoute
  ApiPublicCredentialAgentIdRoute: typeof ApiPublicCredentialAgentIdRoute
  ApiPublicStatusAgentIdRoute: typeof ApiPublicStatusAgentIdRoute
  ApiPublicVerifyAgentIdRoute: typeof ApiPublicVerifyAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/infinity-issuer.json': {
      id: '/.well-known/infinity-issuer.json'
      path: '/.well-known/infinity-issuer.json'
      fullPath: '/.well-known/infinity-issuer.json'
      preLoaderRoute: typeof DotwellKnownInfinityIssuerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$agentId': {
      id: '/verify/$agentId'
      path: '/verify/$agentId'
      fullPath: '/verify/$agentId'
      preLoaderRoute: typeof VerifyAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/credential/$agentId': {
      id: '/api/public/credential/$agentId'
      path: '/api/public/credential/$agentId'
      fullPath: '/api/public/credential/$agentId'
      preLoaderRoute: typeof ApiPublicCredentialAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status/$agentId': {
      id: '/api/public/status/$agentId'
      path: '/api/public/status/$agentId'
      fullPath: '/api/public/status/$agentId'
      preLoaderRoute: typeof ApiPublicStatusAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/$agentId': {
      id: '/api/public/verify/$agentId'
      path: '/api/public/verify/$agentId'
      fullPath: '/api/public/verify/$agentId'
      preLoaderRoute: typeof ApiPublicVerifyAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  DotwellKnownInfinityIssuerDotjsonRoute:
    DotwellKnownInfinityIssuerDotjsonRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  VerifyAgentIdRoute: VerifyAgentIdRoute,
  ApiPublicCredentialAgentIdRoute: ApiPublicCredentialAgentIdRoute,
  ApiPublicStatusAgentIdRoute: ApiPublicStatusAgentIdRoute,
  ApiPublicVerifyAgentIdRoute: ApiPublicVerifyAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
